# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "VEF 2.0 conference"
email: "cuongnguyen@vef2.org"
description: "VEF 2.0 conference"
baseurl: "/zeppelin"
url: "https://apuo.github.io/zeppelin"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "VEF 2.0"
organizerAlternateName: "VEF 2.0 organization"
organizerDescription: "Connects US engineers and scientists"
organizerEmail: "cuong-nguyen@vef2.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://vef2.org/"

# Head
metaKeywords: "event, conference, engineers, google, programming, android, chrome, developers, scienitsts, VEF"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/conference-logo.png"
socialImageSrcTwitter: "/img/seo/conference-logo.png"
socialImageSrcFacebook: "/img/seo/conference-logo.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "About us"}
# - {permalink: "/logistics/", text: "Logistics"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdStuaTowl66Rysu-EoYMTsEM9DAhyM2nOvpSKsUG8JS0jkzA/viewform", text: "Register to present"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdStuaTowl66Rysu-EoYMTsEM9DAhyM2nOvpSKsUG8JS0jkzA/viewform", text: "Register to present"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Vietnamese Scientists and Engineers Conference <typeout> "
eventDate: "August 17-20, 2023"
typeoutTextValues: '"", "Connect", "Collaborate", "Contribute"'
typeoutFallback: "Conference"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdStuaTowl66Rysu-EoYMTsEM9DAhyM2nOvpSKsUG8JS0jkzA/viewform", text: "Register to present"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Location: New Jersey Institute of Technology"
aboutBlock:
 - {title: "Young Vietnamese scholars session", image: "conference.jpg", text: "Presentations of research and projects by Vietnamese high school and undergraduate students via video conferencing" }
 - {title: "Team building activitites", image: "workshop.jpg", text: "Fun team building activities for participants to get to know each other" }
 - {title: "All the ways home", image: "hackathon.jpg", text: "Trends and career opportunities for engineers and scientists in Vietnam in the next five years" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from different locations in the US and Vietnam"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "to network with the best Vietnamese minds in science and engineers"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from academia, industry and management"}
 - {count: "2", specialCharacter: "", info: "types of activities", detail: "professional presentations and networking"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "New Jersey Institute of Technology"
eventLocationLink: "https://goo.gl/maps/enBddrsZX1T3taVs7"
eventStreetAddress: "101 Hudson St"
eventAddressLocality: "Jersey City"
eventAddressLocalityRegion: "New Jersey"
eventPostalCode: "07302"
eventAddressCountry: "United States"
eventStartTime: "2023-08-17T10:00"
eventDoorTime: "09:00"
eventEndTime: "2023-08-20T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
# venueBlockTitle: "Venue"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueSmallImage3: "venue_3.jpg"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Contact us"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Contact us if you want to attend the conference or sponsor the event"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "50"
  priceCurrency: "USD"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "https://apuo.github.io/zeppelin/blog/payment"
  buyButtonText: "Pay Now"
  ticketContentList: ["Attend presentations", "Join team-building activities", "Group night chat in airbnb stay"]
  validFrom: "2023-08-17T10:00"
  validThrough: "2023-08-20T23:59"
 -
  name: "Last Chance"
  price: "60"
  priceCurrency: "USD"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "https://apuo.github.io/zeppelin/blog/payment"
  buyButtonText: "Buy Now"
  ticketContentList: ["Attend presentations", "Join team-building activities", "Group night chat in airbnb stay"]
  validFrom: "2023-08-17T10:00"
  validThrough: "2023-08-20T23:59"
  disabled: true
 -
  name: "Student"
  price: "50"
  priceCurrency: "USD"
  ticketsNumber: "50"
  buyButtonLink: "https://apuo.github.io/zeppelin/blog/payment"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in"
  ticketContentList: ["Attend presentations", "Join team-building activities", "Group night chat in airbnb stay"]
  validFrom: "2023-08-17T10:00"
  validThrough: "2023-08-20T23:59"
  # soldOut: true
  # soldOutText: "Sold Out"

# Footer
socialLinks:
 # - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 # - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://www.facebook.com/VEF2.0/", icon: "facebook"}
 # - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://vef2.org/", text: "VEF2.0"}
 #  - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:cuong-nguyen@vef2.org", text: "cuong-nguyen@vef2.org"}


# # Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Vietnam Education Foundation (VEF) was a US government sponsored program from 2003 to 2018 to send more than 500 top US university Masters and PhDs. To continue expanding the initiative to support future Scientists and Engineers from Vietnam, VEF alumni and friends created  VEF alumni have created VEF 2.0 to extend scholarships and networking opportunities for undergraduate students seek to further their study, master or PhD, in top US insitutions."

# # Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
 # - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 # - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 # - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
 # -
  # title: "Questions?"
  # subCards:
   # -
    # title: "Hotels"
    # links:
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   # -
    # title: "Registration"
    # links:
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   # -
    # title: "Attendance Details"
    # links:
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     # - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# # Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
 # - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 # - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 # - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# # Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# # Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
 # - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 # - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 # - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# # Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "New Jersey Institute of Technology"
# hackathonLocationLink: "https://goo.gl/maps/Y54hrUfscrJgnDem8"
# hackathonStreetAddress: "101 Hudson St"
# hackathonAddressLocality: "Jersey City"
# hackathonAddressLocalityRegion: "New Jersey"
# hackathonPostalCode: "07302"
# hackathonAddressCountry: "United States"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2023-08-17T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2023-08-20T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "40.71600890916713, -74.03514924232938"
# hackathonMapCenterCoordinates: "40.71600890916713, -74.03514924232938"
# hackathonMapMobileCenterCoordinates: "40.71600890916713, -74.03514924232938"
